version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD"]
      timeout: 10s
      retries: 10


  todolist-app:
    container_name: todolist-app
    restart: on-failure
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3306
      MYSQL_DATABASE: todo_list
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  mysql_data: